global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8005']

  - job_name: 'llm'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['llm:8000']

  - job_name: 'asr'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['asr:8001']

  - job_name: 'tts'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tts:8002']

  - job_name: 'avatar'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['avatar:8003']

  - job_name: 'vision'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['vision:8004']

  - job_name: 'qdrant'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['qdrant:6333']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'node'
    static_configs:
      - targets: ['prometheus:9100'] 